<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7ae2293c-b21f-4ce7-8869-9a16033dba25</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Web" Version="2.18.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.20.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MobileStore.Api.Model\MobileStore.Api.Model.csproj" />
    <ProjectReference Include="..\MobileStore.Configuration.Common\MobileStore.Configuration.csproj" />
    <ProjectReference Include="..\MobileStore.Customers\MobileStore.Customers.csproj" />
    <ProjectReference Include="..\MobileStore.Customers.Contracts\MobileStore.Customers.Contracts.csproj" />
    <ProjectReference Include="..\MobileStore.Orders\MobileStore.Orders.csproj" />
    <ProjectReference Include="..\MobileStore.Orders.Contracts\MobileStore.Orders.Contracts.csproj" />
    <ProjectReference Include="..\MobileStore.Products\MobileStore.Products.csproj" />
    <ProjectReference Include="..\MobileStore.Products.Contracts\MobileStore.Products.Contracts.csproj" />
  </ItemGroup>

</Project>
