version: '3.4'
services:
  mobilestore.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - '63959:8080'
      - '63960:8081'
    volumes:
      - '${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro'
      - '${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro'
  mobilestore.email.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8082
      - ASPNETCORE_HTTPS_PORTS=8083
    ports:
      - '8082'
      - '8083'
    volumes:
      - '${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro'
      - '${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro'
