<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MobileStore.Api.Model\MobileStore.Api.Model.csproj" />
    <ProjectReference Include="..\MobileStore.Orders.Contracts\MobileStore.Orders.Contracts.csproj" />
  </ItemGroup>

</Project>
